[workspace]
resolver = "2"
members = ["harvest-verifier", "harvest-campaign", "mock-defindex-vault"]

[workspace.dependencies]
soroban-sdk = "27.0.6"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
