#![cfg(test)]
//! Registry tests against real enrolment proofs.
//!
//! Integration tests in the honest sense: the verifier really runs a BN254
//! pairing over artefacts generated by `circuits/export-enrolment-fixtures.mjs`.
//! Nothing about the enrolment claim is stubbed.

use super::*;
use ark_bn254::Fq;
use ark_ff::{BigInteger, PrimeField};
use harvest_verifier::{HarvestVerifier, HarvestVerifierClient};
use serde::Deserialize;
use soroban_sdk::{
    crypto::bn254::{BN254_G1_SERIALIZED_SIZE, BN254_G2_SERIALIZED_SIZE},
    testutils::{Address as _, Ledger as _},
    Address, Env, String as SorobanString, Vec,
};
use std::str::FromStr;
use std::string::String as StdString;
use std::vec::Vec as StdVec;

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct VkJson {
    vk_alpha_1: [StdString; 3],
    vk_beta_2: [[StdString; 2]; 3],
    vk_gamma_2: [[StdString; 2]; 3],
    vk_delta_2: [[StdString; 2]; 3],
    #[serde(rename = "IC")]
    ic: StdVec<[StdString; 3]>,
}

#[derive(Deserialize)]
struct ProofJson {
    pi_a: [StdString; 3],
    pi_b: [[StdString; 2]; 3],
    pi_c: [StdString; 3],
}

#[derive(Deserialize)]
struct ClaimJson {
    issuer_ax: StdString,
    issuer_ay: StdString,
    threshold_kg: u64,
    season: u32,
    nullifier: StdString,
    address_binding: StdString,
}

#[derive(Deserialize)]
struct FixtureJson {
    #[serde(rename = "farmerAddress")]
    farmer_address: StdString,
    claim: ClaimJson,
    proof: ProofJson,
}

fn data_dir(crate_name: &str) -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join(crate_name)
        .join("tests")
        .join("data")
}

fn fixture(crate_name: &str, name: &str) -> FixtureJson {
    let path = data_dir(crate_name).join(name);
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing {}: {e}\nRun `node export-enrolment-fixtures.mjs` in circuits/",
            path.display()
        )
    });
    serde_json::from_str(&raw).expect("bad fixture json")
}

/// Big-endian, flag bits clear.
fn fq_be(decimal: &str) -> [u8; 32] {
    let be = Fq::from_str(decimal).expect("bad Fq").into_bigint().to_bytes_be();
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

fn g1(env: &Env, x: &str, y: &str) -> Bn254G1Affine {
    let mut buf = [0u8; BN254_G1_SERIALIZED_SIZE];
    buf[0..32].copy_from_slice(&fq_be(x));
    buf[32..64].copy_from_slice(&fq_be(y));
    Bn254G1Affine::from_array(env, &buf)
}

/// Imaginary part first, opposite to snarkjs' ordering.
fn g2(env: &Env, x0: &str, x1: &str, y0: &str, y1: &str) -> Bn254G2Affine {
    let mut buf = [0u8; BN254_G2_SERIALIZED_SIZE];
    buf[0..32].copy_from_slice(&fq_be(x1));
    buf[32..64].copy_from_slice(&fq_be(x0));
    buf[64..96].copy_from_slice(&fq_be(y1));
    buf[96..128].copy_from_slice(&fq_be(y0));
    Bn254G2Affine::from_array(env, &buf)
}

fn hex32(env: &Env, hex: &str) -> BytesN<32> {
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        *b = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    BytesN::from_array(env, &out)
}

fn proof_of(env: &Env, p: &ProofJson) -> Proof {
    Proof {
        a: g1(env, &p.pi_a[0], &p.pi_a[1]),
        b: g2(env, &p.pi_b[0][0], &p.pi_b[0][1], &p.pi_b[1][0], &p.pi_b[1][1]),
        c: g1(env, &p.pi_c[0], &p.pi_c[1]),
    }
}

fn claim_of(env: &Env, c: &ClaimJson) -> CapacityClaim {
    CapacityClaim {
        issuer_ax: hex32(env, &c.issuer_ax),
        issuer_ay: hex32(env, &c.issuer_ay),
        threshold_kg: c.threshold_kg,
        season: c.season,
        nullifier: hex32(env, &c.nullifier),
        address_binding: hex32(env, &c.address_binding),
    }
}

/// The same two values in the verifier crate's own types, for the one test
/// that calls the verifier directly instead of going through the registry.
/// The structs are wire-identical; Rust just does not know that.
fn verifier_claim_of(env: &Env, c: &ClaimJson) -> harvest_verifier::CapacityClaim {
    harvest_verifier::CapacityClaim {
        issuer_ax: hex32(env, &c.issuer_ax),
        issuer_ay: hex32(env, &c.issuer_ay),
        threshold_kg: c.threshold_kg,
        season: c.season,
        nullifier: hex32(env, &c.nullifier),
        address_binding: hex32(env, &c.address_binding),
    }
}

fn verifier_proof_of(env: &Env, p: &ProofJson) -> harvest_verifier::Proof {
    harvest_verifier::Proof {
        a: g1(env, &p.pi_a[0], &p.pi_a[1]),
        b: g2(env, &p.pi_b[0][0], &p.pi_b[0][1], &p.pi_b[1][0], &p.pi_b[1][1]),
        c: g1(env, &p.pi_c[0], &p.pi_c[1]),
    }
}

fn vk_from(env: &Env, crate_name: &str) -> harvest_verifier::VerificationKey {
    let path = data_dir(crate_name).join("verification_key.json");
    let j: VkJson = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    let mut ic = Vec::new(env);
    for p in &j.ic {
        ic.push_back(g1(env, &p[0], &p[1]));
    }
    harvest_verifier::VerificationKey {
        alpha: g1(env, &j.vk_alpha_1[0], &j.vk_alpha_1[1]),
        beta: g2(env, &j.vk_beta_2[0][0], &j.vk_beta_2[0][1], &j.vk_beta_2[1][0], &j.vk_beta_2[1][1]),
        gamma: g2(env, &j.vk_gamma_2[0][0], &j.vk_gamma_2[0][1], &j.vk_gamma_2[1][0], &j.vk_gamma_2[1][1]),
        delta: g2(env, &j.vk_delta_2[0][0], &j.vk_delta_2[0][1], &j.vk_delta_2[1][0], &j.vk_delta_2[1][1]),
        ic,
    }
}

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

/// ÇKS | DEED | LAND -- what the registry insists on. TARSİM stays optional.
const REQUIRED_MASK: u64 = 1 | 2 | 8;

struct World<'a> {
    env: Env,
    registry: HarvestRegistryClient<'a>,
    verifier: HarvestVerifierClient<'a>,
}

/// A registry wired to a verifier holding the **enrolment** circuit's key.
fn world() -> World<'static> {
    let env = Env::default();
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();
    env.ledger().with_mut(|l| l.timestamp = 1_700_000_000);

    let admin = Address::generate(&env);

    let verifier_id = env.register(HarvestVerifier, ());
    let verifier = HarvestVerifierClient::new(&env, &verifier_id);
    verifier.initialize(&admin, &vk_from(&env, "harvest-registry"));

    // The cooperative whose key signed the fixtures.
    let fx = fixture("harvest-registry", "valid.json");
    verifier.accredit_issuer(
        &hex32(&env, &fx.claim.issuer_ax),
        &hex32(&env, &fx.claim.issuer_ay),
        &SorobanString::from_str(&env, "Giresun Findik Tarim Satis Kooperatifi"),
    );

    let registry_id = env.register(HarvestRegistry, ());
    let registry = HarvestRegistryClient::new(&env, &registry_id);
    registry.initialize(&admin, &verifier_id, &REQUIRED_MASK);

    World { env, registry, verifier }
}

fn farmer_of(env: &Env, fx: &FixtureJson) -> Address {
    Address::from_string(&SorobanString::from_str(env, &fx.farmer_address))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn a_cooperative_checked_enrolment_is_recorded_without_naming_anyone() {
    let w = world();
    let fx = fixture("harvest-registry", "valid.json");
    let farmer = farmer_of(&w.env, &fx);

    let count = w.registry.register(
        &farmer,
        &claim_of(&w.env, &fx.claim),
        &proof_of(&w.env, &fx.proof),
    );
    assert_eq!(count, 1);
    assert_eq!(w.registry.registered_count(), 1);

    let nullifier = hex32(&w.env, &fx.claim.nullifier);
    assert!(w.registry.is_registered(&nullifier));
    assert!(w.registry.is_address_registered(&farmer));

    let reg = w.registry.registration_of(&nullifier);
    // The mask is everything the chain learns about the paperwork.
    assert_eq!(reg.doc_mask, REQUIRED_MASK, "ÇKS + deed + land, and nothing else");
    assert_eq!(reg.season, 2026);
    assert_eq!(reg.farmer, farmer);
    assert_eq!(reg.registered_at, 1_700_000_000);
}

#[test]
fn the_same_credential_cannot_enrol_twice() {
    let w = world();
    let fx = fixture("harvest-registry", "valid.json");
    let farmer = farmer_of(&w.env, &fx);
    let claim = claim_of(&w.env, &fx.claim);
    let proof = proof_of(&w.env, &fx.proof);

    w.registry.register(&farmer, &claim, &proof);

    // Same proof, same nullifier. This is the whole point of spending it.
    let err = w.registry.try_register(&farmer, &claim, &proof).err().unwrap().unwrap();
    assert_eq!(err, RegistryError::AlreadyRegistered);
    assert_eq!(w.registry.registered_count(), 1);
}

#[test]
fn a_holding_under_the_eligibility_floor_is_refused_on_the_mask() {
    let w = world();
    let fx = fixture("harvest-registry", "insufficient.json");
    let farmer = farmer_of(&w.env, &fx);

    // Nothing is forged: the proof is valid and the cooperative really did check
    // both documents. The circuit simply withheld the land bit, so the mask is 3.
    assert_eq!(fx.claim.threshold_kg, 1 | 2);

    let err = w
        .registry
        .try_register(
            &farmer,
            &claim_of(&w.env, &fx.claim),
            &proof_of(&w.env, &fx.proof),
        )
        .err()
        .unwrap()
        .unwrap();
    assert_eq!(err, RegistryError::InsufficientDocuments);
    assert_eq!(w.registry.registered_count(), 0);
}

#[test]
fn a_capacity_proof_does_not_verify_against_the_enrolment_key() {
    // Both circuits publish six signals in the same order, so a capacity claim
    // deserialises cleanly into the enrolment claim struct and reaches the
    // pairing check intact. The verification key is the only thing separating
    // the two proof types, so test exactly that, at the verifier.
    let w = world();
    let fx = fixture("harvest-verifier", "valid.json");
    let farmer = farmer_of(&w.env, &fx);

    assert!(
        !w.verifier.check_capacity(
            &farmer,
            &verifier_claim_of(&w.env, &fx.claim),
            &verifier_proof_of(&w.env, &fx.proof),
        ),
        "a capacity proof must not verify under the enrolment circuit's key"
    );
}

#[test]
fn a_capacity_claim_cannot_be_smuggled_through_the_registry() {
    // Belt and braces on the same idea, one level up. The capacity fixture
    // proves ">= 40000 kg", and 40000 carries none of the mask bits the
    // registry requires, so it is turned away before the pairing even runs.
    let w = world();
    let fx = fixture("harvest-verifier", "valid.json");
    let farmer = farmer_of(&w.env, &fx);
    assert_ne!(fx.claim.threshold_kg & REQUIRED_MASK, REQUIRED_MASK);

    let err = w
        .registry
        .try_register(
            &farmer,
            &claim_of(&w.env, &fx.claim),
            &proof_of(&w.env, &fx.proof),
        )
        .err()
        .unwrap()
        .unwrap();
    assert_eq!(err, RegistryError::InsufficientDocuments);
}

#[test]
#[should_panic(expected = "Error(Contract, #6)")]
fn an_enrolment_cannot_be_replayed_from_another_account() {
    let w = world();
    let fx = fixture("harvest-registry", "valid.json");
    let bystander = Address::generate(&w.env);

    // A valid proof, lifted and submitted by someone else. The verifier
    // recomputes the address binding from the caller and refuses.
    w.registry.register(
        &bystander,
        &claim_of(&w.env, &fx.claim),
        &proof_of(&w.env, &fx.proof),
    );
}

#[test]
fn an_unregistered_account_reports_as_such() {
    let w = world();
    let stranger = Address::generate(&w.env);
    assert!(!w.registry.is_address_registered(&stranger));
    assert_eq!(w.registry.registered_count(), 0);

    let (_, _, required) = w.registry.config();
    assert_eq!(required, REQUIRED_MASK);
}
